// Bleep touch remote enclosure, v1 -- design 1b "Pebble", own main board + bare 3.5" panel.
// All dimensions come from params.scad, generated by ../layout.py.
//
// Render a part from the command line:
//   openscad -D 'part="front"' -o stl/front_shell.stl remote.scad
// parts: front, ir_window, sensor_window, back, caps, caps_labels, assembly, interference
//
// Coordinates: layout.py uses shell coords with y pointing DOWN from the
// top (IR) end. Here everything is placed at [x, -y] so the top end is +y.

include <params.scad>

part = "assembly";
labels = true;          // engrave key labels on the caps
$fn = 48;

EF = 2.0;               // front edge round-over
EB = 1.0;               // back edge round-over
EPS = 0.01;

function S(p) = [p[0], -p[1]];

// ---------------------------------------------------------------- outline
module outline2d(off = 0) {
    hull() {
        for (c = [[R_TOP, R_TOP], [W - R_TOP, R_TOP]]) translate(S(c)) circle(r = max(R_TOP + off, 0.1));
        for (c = [[R_BOT, L - R_BOT], [W - R_BOT, L - R_BOT]]) translate(S(c)) circle(r = max(R_BOT + off, 0.1));
    }
}

// Full rounded solid, z 0..H. The outline is convex, so a hull of offset
// slices gives the round-overs on the front and back edges.
module solid() {
    n = 6;
    hull() {
        for (i = [0:n]) {
            a = 90 * i / n;
            translate([0, 0, H - EF + EF * sin(a) - EPS]) linear_extrude(EPS) outline2d(-EF + EF * cos(a));
            translate([0, 0, EB - EB * sin(a)]) linear_extrude(EPS) outline2d(-EB + EB * cos(a));
        }
    }
}

module slab(z0, z1) {
    intersection() {
        solid();
        translate([-1, -L - 1, z0]) cube([W + 2, L + 2, z1 - z0]);
    }
}

module rrect(size, r, center_p) {
    translate(S(center_p)) offset(r = r) square([size[0] - 2 * r, size[1] - 2 * r], center = true);
}

// ---------------------------------------------------------------- key caps
module pill2d(w, h) { hull() for (s = [-1, 1]) translate([s * (w / 2 - h / 2), 0]) circle(d = h); }

module halfplane_ccw(theta, g) { rotate(theta) translate([-60, g]) square([120, 60]); }
module halfplane_cw(theta, g)  { rotate(theta) translate([-60, -60 - g]) square([120, 60]); }

module wedge2d(angle, g) {
    intersection() { halfplane_ccw(angle - 45, g); halfplane_cw(angle + 45, g); }
}

module annulus2d(r0, r1) { difference() { circle(r = r1, $fn = 96); circle(r = r0, $fn = 96); } }

seg_g = DPAD_BRIDGE_W / 2 + CAP_HOLE_CLR;

// 2D outline of a cap, absolute position. k = [name, type, sw_pos, angle, label]
module cap2d(k) {
    t = k[1];
    if (t == "ring") translate(S(DPAD_C)) annulus2d(DPAD_R_IN, DPAD_R_OUT);
    else if (t == "ok") translate(S(DPAD_C)) circle(r = DPAD_OK_R, $fn = 96);
    else if (t == "round") translate(S(k[2])) circle(r = ROUND_R);
    else if (t == "pill") translate(S(k[2])) pill2d(PILL[0], PILL[1]);
    else if (t == "volL" || t == "volR")
        translate(S(VOL_C)) intersection() {
            pill2d(VOL_BAR[0], VOL_BAR[1]);
            translate([t == "volL" ? -VOL_BAR[0] / 2 - 1 : VOL_SPLIT / 2, -VOL_BAR[1]])
                square([VOL_BAR[0] / 2 + 1 - VOL_SPLIT / 2, 2 * VOL_BAR[1]]);
        }
}

// Outline of the hole in the front wall for a cap (before clearance).
module hole_base2d(k) {
    t = k[1];
    if (t == "volL" || t == "volR") translate(S(VOL_C)) pill2d(VOL_BAR[0], VOL_BAR[1]);
    else if (t == "ring") translate(S(DPAD_C)) circle(r = DPAD_R_OUT, $fn = 96);     // one hole for ring + OK
    else cap2d(k);
}

// Where a cap's flange may extend (keeps flanges off bridges and neighbours).
module flange_mask2d(k) {
    t = k[1];
    if (t == "ring") translate(S(DPAD_C)) annulus2d(DPAD_R_OUT - 1, 60);       // flange only outward
    else if (t == "ok") translate(S(DPAD_C)) circle(r = 0.01);                  // OK has its own flange under the ring
    else if (t == "volL" || t == "volR")
        translate(S(VOL_C)) translate([t == "volL" ? -40 - VOL_SPLIT / 2 : VOL_SPLIT / 2, -20]) square([40, 40]);
    else translate(S(k[2])) square(60, center = true);
}

// Key icons, about 4.5 mm across (ICON_F x the 6 mm drawings below), centred
// on the origin. Line strokes stay 0.65 mm whatever the scale and every gap
// stays >= 0.5 mm, so the inlays still print with a 0.4 mm nozzle.
ICON_F = 0.75;
module icon2d(name) {
    f = ICON_F;
    s = 0.65;  // stroke
    if (name == "@back") {
        // return arrow: U-turn on the right, arrowhead pointing left at the top
        r = 2.0 * f;
        translate([0, -0.4 * f]) {
            translate([0.7 * f, 0]) intersection() {
                annulus2d(r - s / 2, r + s / 2);
                translate([0, -5]) square(10);
            }
            translate([-1.0 * f, r - s / 2]) square([1.7 * f, s]);          // top stem
            translate([-1.6 * f, -r - s / 2]) square([2.3 * f, s]);         // bottom stem
            polygon([[-2.9 * f, r], [-1.0 * f, r + 1.3 * f], [-1.0 * f, r - 1.3 * f]]);   // arrowhead
        }
    } else if (name == "@home") {
        scale(f) difference() {
            union() {
                polygon([[-3.1, 0.3], [3.1, 0.3], [0, 3.2]]);         // roof
                translate([-2.1, -2.9]) square([4.2, 3.3]);            // body
            }
            translate([-0.6, -2.95]) square([1.2, 1.9]);               // door
        }
    } else if (name == "@mute") {
        translate([-0.6 * f, 0]) {
            scale(f) {
                translate([-2.5, -1.0]) square([1.1, 2.0]);            // speaker body
                polygon([[-1.4, -1.0], [-1.4, 1.0], [0.4, 2.4], [0.4, -2.4]]);   // cone
            }
            for (a = [45, -45]) translate([2.3 * f, 0]) rotate(a) square([3.0 * f, s], center = true);   // X
        }
    } else if (name == "@youtube") {
        // play button: rounded rectangle with the triangle left in the cap colour
        scale(f) difference() {
            offset(r = 1.2) square([4.4, 2.2], center = true);
            polygon([[-0.8, -1.15], [-0.8, 1.15], [1.25, 0]]);
        }
    } else if (name == "@netflix") {
        // bold N
        scale(f) {
            translate([-1.7, -2.5]) square([0.95, 5.0]);
            translate([0.75, -2.5]) square([0.95, 5.0]);
            polygon([[-1.7, 2.5], [-0.75, 2.5], [1.7, -2.5], [0.75, -2.5]]);
        }
    } else if (name == "@plex") {
        // chevron
        scale(f) polygon([[-1.5, 2.6], [0.1, 2.6], [2.0, 0], [0.1, -2.6], [-1.5, -2.6], [0.4, 0]]);
    }
}

// Labels and icons are two-colour inlays: the cap body has a recess and a
// separate label body fills it flush with the key top (print both in one job
// on a multi-material printer, labels in the second colour).
LABEL_DEPTH = 0.6;   // 3 layers at 0.2 mm, so a light colour hides a dark body

// 2D outline of a cap's label/icon, absolute position.
module cap_label2d(k) {
    t = k[1];
    if (t == "ring") {
        // four dots mark the press points (drawn once, with the UP entry)
        if (k[0] == "UP") translate(S(DPAD_C)) for (a = [0:90:270]) rotate(a)
            translate([(DPAD_R_IN + DPAD_R_OUT) / 2, 0]) circle(r = 0.75, $fn = 24);
    } else if (labels && len(k[4]) > 0 && k[4][0] == "@") {
        translate(S(k[2])) icon2d(k[4]);
    } else if (labels && (t == "volL" || t == "volR")) {
        // + / - drawn as bars (font glyphs sit off the cap's centre line)
        translate(S([VOL_C[0] + (t == "volL" ? -1 : 1) * VOL_BAR[0] / 4, VOL_C[1]])) {
            square([3.2, 0.75], center = true);
            if (t == "volR") square([0.75, 3.2], center = true);
        }
    } else if (labels && k[4] != "") {
        p = (t == "ok") ? DPAD_C : k[2];
        sz = t == "ok" ? 2.6 : 2.0;
        translate(S(p)) text(k[4], size = sz, font = "Liberation Sans:style=Bold", halign = "center", valign = "center");
    }
}

module cap_engrave(k) {   // recess cut into the cap body
    translate([0, 0, H + CAP_PROTRUDE - LABEL_DEPTH]) linear_extrude(LABEL_DEPTH + 1) cap_label2d(k);
}

module cap_label(k) {     // the inlay that fills the recess, flush with the top
    translate([0, 0, H + CAP_PROTRUDE - LABEL_DEPTH]) linear_extrude(LABEL_DEPTH)
        intersection() { cap_label2d(k); cap2d(k); }
}

// Generic cap: body through the wall, 45-degree seat that sits in a matching
// countersink on the inside of the wall, flange plate, stem onto the switch.
// Printed top-down, so the seat is the only overhang and it is 45 degrees.
module cap_generic(shape_children_k, stems) {
    k = shape_children_k;
    nz = 4;
    difference() {
        union() {
            // body
            translate([0, 0, Z_FRONT_IN + CAP_FLANGE]) linear_extrude(H + CAP_PROTRUDE - Z_FRONT_IN - CAP_FLANGE)
                offset(delta = -0.0) cap2d(k);
            // 45-degree seat inside the wall countersink
            for (i = [0:nz - 1]) {
                f = CAP_FLANGE * (1 - i / nz);
                translate([0, 0, Z_FRONT_IN + CAP_FLANGE * i / nz - EPS]) linear_extrude(CAP_FLANGE / nz + 2 * EPS)
                    union() { cap2d(k); intersection() { offset(r = f) cap2d(k); flange_mask2d(k); } }
            }
            // flange plate under the wall
            translate([0, 0, Z_FRONT_IN - CAP_FLANGE]) linear_extrude(CAP_FLANGE + EPS)
                union() { cap2d(k); intersection() { offset(r = CAP_FLANGE) cap2d(k); flange_mask2d(k); } }
            // stem(s) onto the switch actuator
            for (s = stems) translate([s[0], -s[1], Z_ACTUATOR - EPS])
                cylinder(d = 3.4, h = Z_FRONT_IN - CAP_FLANGE - Z_ACTUATOR + 2 * EPS);
        }
        cap_engrave(k);
        // soften the top edge a little
    }
}

// The OK button: no wall to seat on (it shares the ring's hole), so its flange
// sits DPAD_OK_DROP under the ring's inner edge, overlapping it by DPAD_OK_LIP.
module ok_cap(k) {
    fl_top = Z_FRONT_IN - CAP_FLANGE - DPAD_OK_DROP;
    difference() {
        union() {
            translate([0, 0, fl_top]) linear_extrude(H + CAP_PROTRUDE - fl_top) cap2d(k);
            translate([DPAD_C[0], -DPAD_C[1], fl_top - CAP_FLANGE]) cylinder(r = DPAD_R_IN + DPAD_OK_LIP, h = CAP_FLANGE + EPS, $fn = 96);
            translate([DPAD_C[0], -DPAD_C[1], Z_ACTUATOR - EPS]) cylinder(d = 3.4, h = fl_top - CAP_FLANGE - Z_ACTUATOR + 2 * EPS);
        }
        cap_engrave(k);
    }
}

// The ring is one cap with a stem on each direction switch (built with the
// UP entry; the other three ring entries add nothing).
module cap(k) {
    if (k[1] == "ring") { if (k[0] == "UP") cap_generic(k, [for (kk = KEYS) if (kk[1] == "ring") kk[2]]); }
    else if (k[1] == "ok") ok_cap(k);
    else cap_generic(k, [k[2]]);
}

// PWR key: pill cap in the row under the screen, same seat/flange system.
PWR_K = ["PWR", "pwr", PWR_KEY, 0, ""];
module pwr2d() { translate(S(PWR_KEY)) pill2d(PWR_PILL[0], PWR_PILL[1]); }

module pwr_cap() {
    nz = 4;
    union() {
        translate([0, 0, Z_FRONT_IN + CAP_FLANGE]) linear_extrude(H + CAP_PROTRUDE - Z_FRONT_IN - CAP_FLANGE) pwr2d();
        for (i = [0:nz - 1]) translate([0, 0, Z_FRONT_IN + CAP_FLANGE * i / nz - EPS])
            linear_extrude(CAP_FLANGE / nz + 2 * EPS) offset(r = CAP_FLANGE * (1 - i / nz)) pwr2d();
        translate([0, 0, Z_FRONT_IN - CAP_FLANGE]) linear_extrude(CAP_FLANGE + EPS) offset(r = CAP_FLANGE) pwr2d();
        translate([PWR_KEY[0], -PWR_KEY[1], Z_ACTUATOR - EPS]) cylinder(d = 3.4, h = Z_FRONT_IN - CAP_FLANGE - Z_ACTUATOR + 2 * EPS);
    }
}

// ---------------------------------------------------------------- front shell
// Cuts applied after the internal posts/bosses are added (the cavity itself
// is removed earlier, in front_shell, so it doesn't eat the posts).
module front_cuts() {
    // glass pocket (the panel stack sits in the cavity below it)
    translate([0, 0, Z_FRONT_IN - 1]) linear_extrude(Z_LENS_TOP - Z_FRONT_IN + 1)
        rrect([LENS[0] + 2 * CLEAR, LENS[1] + 2 * CLEAR], LENS[2] + CLEAR, LENS_C);
    // screen window: the frame overlaps the glass by LIP_OVER, chamfered outside
    win = [LENS[0] - 2 * LIP_OVER, LENS[1] - 2 * LIP_OVER];
    hull() {
        translate([0, 0, Z_LENS_TOP - 1]) linear_extrude(EPS) rrect(win, 0.8, LENS_C);
        translate([0, 0, H - 0.5]) linear_extrude(EPS) rrect(win, 0.8, LENS_C);
        translate([0, 0, H + EPS]) linear_extrude(EPS) rrect([win[0] + 1.0, win[1] + 1.0], 1.3, LENS_C);
    }
    // key holes + countersinks
    for (k = KEYS) key_hole(k);
    // PWR key hole
    translate([0, 0, Z_FRONT_IN - 1]) linear_extrude(H) offset(delta = CAP_HOLE_CLR) pwr2d();
    for (i = [0:3]) translate([0, 0, Z_FRONT_IN - EPS + CAP_FLANGE * i / 4])
        linear_extrude(CAP_FLANGE / 4 + 2 * EPS) offset(r = CAP_HOLE_CLR + CAP_FLANGE * (1 - i / 4)) pwr2d();
    // IR window through the top end wall (centred on the LED axis), with a
    // recess inside for the clear window's flange
    translate([IR_WINDOW[0] - IR_WINDOW[1] / 2, -WALL - 1, IR_WINDOW[3] - IR_WINDOW[2] / 2]) cube([IR_WINDOW[1], WALL + 2, IR_WINDOW[2]]);
    translate([IR_WINDOW[0] - IR_WINDOW[1] / 2 - IR_FLANGE[0], -WALL - 0.01, IR_WINDOW[3] - IR_WINDOW[2] / 2 - IR_FLANGE[1]])
        cube([IR_WINDOW[1] + 2 * IR_FLANGE[0], IR_FLANGE[2] + 0.01, IR_WINDOW[2] + 2 * IR_FLANGE[1]]);
    // USB-C: plug opening through the bottom wall, and a pocket inside that
    // thins the wall to USB_WALL_T so the receptacle face sits close to the outside
    translate([USB_X, -L - 1, USB_Z]) rotate([-90, 0, 0]) linear_extrude(WALL + 2)
        offset(r = USB_OPEN[1] / 2 - 0.01) square([USB_OPEN[0] - USB_OPEN[1], 0.02], center = true);
    translate([USB_X - 7.0, -(L - USB_WALL_T), BACK_T - 1]) cube([14.0, WALL - USB_WALL_T + 1, min(USB_Z + 4.0, Z_FRONT_IN) - BACK_T + 1]);
    // sensor window under the screen: a pill recess for the clear window, and a
    // hole through it over the IR receiver (learning) and the light sensor
    translate([0, 0, H - WIN_DEPTH]) linear_extrude(1) sensor_win2d();
    for (h = SENSOR_HOLES) translate([h[0], -h[1], Z_FRONT_IN - 1]) cylinder(d = h[2], h = H, $fn = 40);
    // grooves in the top wall for the back plate's snap fingers
    for (t = TOP_TABS) translate([t[0] - t[1] / 2 - 0.3, -(WALL + SNAP_GAP), SNAP_Z])
        rotate([0, 90, 0]) linear_extrude(t[1] + 0.6) polygon([[0.75, 0], [-0.75, 0], [0, SNAP_BUMP + 0.1]]);
    // heat-set insert holes (from the backplane side)
    for (p = concat(KEY_HOLES, TOP_BOSSES, BOT_BOSSES)) translate([p[0], -p[1], Z_BP_TOP - EPS]) cylinder(d = INSERT_HOLE_D, h = INSERT_HOLE_DEPTH);
}

module key_hole(k) {
    translate([0, 0, Z_FRONT_IN - 1]) linear_extrude(H) offset(delta = CAP_HOLE_CLR) hole_base2d(k);
    for (i = [0:3]) translate([0, 0, Z_FRONT_IN - EPS + CAP_FLANGE * i / 4])
        linear_extrude(CAP_FLANGE / 4 + 2 * EPS) intersection() {
            offset(r = CAP_HOLE_CLR + CAP_FLANGE * (1 - i / 4)) hole_base2d(k);
            offset(delta = CAP_HOLE_CLR) flange_mask2d(k);
        }
}

module front_adds() {
    // posts that land on the backplane (key area) and corner bosses; all take inserts
    for (p = KEY_HOLES) translate([p[0], -p[1], Z_BP_TOP]) cylinder(d = POST_D, h = Z_FRONT_IN - Z_BP_TOP + EPS);
    for (p = concat(TOP_BOSSES, BOT_BOSSES)) translate([p[0], -p[1], Z_BP_TOP]) cylinder(d = BOSS_D, h = Z_FRONT_IN - Z_BP_TOP + EPS);
}

module front_shell() {
    difference() {
        union() {
            difference() { slab(BACK_T, H); front_cuts_cavity_only(); }
            intersection() { front_adds(); translate([0, 0, BACK_T]) linear_extrude(H) outline2d(-0.5); }
        }
        front_cuts();
    }
}

// Windows: two small parts printed separately in translucent PETG and fitted by hand
// (a drop of clear glue holds each one).
//  - sensor window: goes in from the front. The pill sits flush in its recess
//    in the front face, with a peg down through each hole; the light sensor's
//    peg runs on to just above the sensor as a light pipe (the IR receiver's
//    lens sits right under the wall anyway). Printed pill face down.
//  - IR window: goes in from the inside, before the board. A plug fills the
//    slot in the top wall, flush outside, and its flange sits in the recess on
//    the inside, so it can't be pushed out. Printed flange down.
WIN_DEPTH = 0.6;
WIN_CLR = 0.1;          // per side, between a window and the shell (press-in fit)
module sensor_win2d() { translate(S(SENSOR_WIN)) pill2d(SENSOR_WIN[2], SENSOR_WIN[3]); }
module sensor_window() {
    translate([0, 0, H - WIN_DEPTH]) linear_extrude(WIN_DEPTH) offset(delta = -WIN_CLR) sensor_win2d();
    for (i = [0:len(SENSOR_HOLES) - 1]) {
        h = SENSOR_HOLES[i];
        z0 = i == 1 ? ALS_PIPE_Z0 : Z_FRONT_IN;          // [1] is the light sensor's hole
        translate([h[0], -h[1], z0]) cylinder(d = h[2] - 2 * WIN_CLR, h = H - WIN_DEPTH - z0 + EPS, $fn = 40);
    }
}
module ir_window() {
    x0 = IR_WINDOW[0] - IR_WINDOW[1] / 2; z0 = IR_WINDOW[3] - IR_WINDOW[2] / 2;
    translate([x0 + WIN_CLR, -WALL, z0 + WIN_CLR]) cube([IR_WINDOW[1] - 2 * WIN_CLR, WALL, IR_WINDOW[2] - 2 * WIN_CLR]);
    translate([x0 - IR_FLANGE[0] + WIN_CLR, -WALL, z0 - IR_FLANGE[1] + WIN_CLR])
        cube([IR_WINDOW[1] + 2 * IR_FLANGE[0] - 2 * WIN_CLR, IR_FLANGE[2], IR_WINDOW[2] + 2 * IR_FLANGE[1] - 2 * WIN_CLR]);
}
IR_FLANGE = [1.5, 1.2, 0.8];   // the recess round the IR slot, inside the top wall: x and z overhang, depth
module windows() { sensor_window(); ir_window(); }

module front_cuts_cavity_only() { translate([0, 0, -1]) linear_extrude(Z_FRONT_IN + 1) outline2d(-WALL); }

// ---------------------------------------------------------------- back plate
module counterbored_hole(p) {
    translate([p[0], -p[1], -1]) cylinder(d = SCREW_CLR_D, h = 30, $fn = 24);
    translate([p[0], -p[1], -1]) cylinder(d = SCREW_HEAD_D, h = 1 + 1.2, $fn = 32);
}

module fence_corners(c, size, h, t = 1.0, arm = 6) {
    for (sx = [-1, 1], sy = [-1, 1]) translate([c[0] + sx * size[0] / 2, -c[1] + sy * size[1] / 2, BACK_T - EPS]) {
        translate([sx > 0 ? 0 : -t, sy > 0 ? -arm + t : -t, 0]) cube([t, arm, h]);
        translate([sx > 0 ? -arm + t : -t, sy > 0 ? 0 : -t, 0]) cube([arm, t, h]);
    }
}

// Snap fingers: there is no room for screw bosses at the top end (the glass
// runs up to it), so two fingers on the back plate's top edge click into
// grooves in the top wall. Their bump is a ridge sloped on both faces, so the
// plate snaps in and, once the screws are out, pulls off again.
SNAP_T = 1.0;                       // finger thickness (y)
SNAP_GAP = 0.15;                    // finger to wall
SNAP_TOP = BACK_T + 4.4;            // finger tip height
SNAP_BUMP = 0.4;                    // how far the ridge stands out (0.25 into the wall)
SNAP_Z = SNAP_TOP - 0.9;            // ridge height
module snap_fingers() {
    for (t = TOP_TABS) translate([t[0] - t[1] / 2, -(WALL + SNAP_GAP) - SNAP_T, BACK_T - EPS]) {
        cube([t[1], SNAP_T, SNAP_TOP - BACK_T]);
        // the ridge on the outer (wall) face, a triangle in y-z
        translate([0, SNAP_T, SNAP_Z - BACK_T]) rotate([0, 90, 0]) linear_extrude(t[1])
            polygon([[0.6, 0], [-0.6, 0], [0, SNAP_BUMP]]);
    }
}

// The back plate (flat back, 2026-10-09): a flat 1.5 mm plate with the locating
// lip and only the board's supports on it -- rails under the board's side edges
// (under the screen), a standoff round each of its two screws and a pillar
// under each key switch. The board is screwed to the front shell on its own,
// so the plate takes only the two bottom screws; snap fingers hold its top end.
// Everything else between the plate and the board is open: the flat cell under
// the screen, the ESP32 module, the motor, the board screws' heads and the
// battery / motor / USB-C solder joints.
module back_plate() {
    lip_h = 1.5;
    sup_h = Z_BP_BOT - BACK_T + EPS;
    difference() {
        union() {
            slab(0, BACK_T);
            difference() {
                translate([0, 0, BACK_T - EPS]) linear_extrude(lip_h) difference() {
                    outline2d(-WALL - 0.25);
                    outline2d(-BP_LIP_IN);
                }
                for (p = concat(TOP_BOSSES, BOT_BOSSES)) translate([p[0], -p[1], 0]) cylinder(d = BOSS_D + 1.5, h = 10);
                translate([USB_X - 7.5, -L - 1, 0]) cube([15, WALL + 12, 10]);
            }
            translate([0, 0, BACK_T - EPS]) linear_extrude(sup_h) intersection() {
                outline2d(-WALL - 0.25);
                union() {
                    for (r = RAILS) translate([r[0], -r[3]]) square([r[2] - r[0], r[3] - r[1]]);
                    for (p = STANDOFFS) translate(S(p)) circle(d = p[2]);
                    for (p = PILLARS) translate(S(p)) circle(d = p[2], $fn = 32);
                }
            }
            fence_corners(BATT_C, [BATT[0] + 0.6, BATT[1] + 0.6], 1.5, t = 0.6);
            snap_fingers();
        }
        for (p = PLATE_SCREWS) counterbored_hole(p);
        // slot to the EN/GND reset pads on the board's underside
        translate([EN_SLOT[0], -EN_SLOT[1], -1]) linear_extrude(BACK_T + 2)
            hull() for (s = [-1, 1]) translate([s * (EN_SLOT[2] - EN_SLOT[3]) / 2, 0]) circle(d = EN_SLOT[3], $fn = 24);
    }
}

// ---------------------------------------------------------------- parts on the print bed
module front_print() { translate([0, 0, H]) rotate([180, 0, 0]) front_shell(); }   // front face on the bed

module cap_on_bed(k, ox, oy, c) {
    // flip so the cap top sits on the bed
    translate([ox, oy, H + CAP_PROTRUDE]) rotate([180, 0, 0]) translate([-c[0], c[1], 0]) children();
}

// mode "body": the caps; mode "labels": just their inlays, in the same spots.
// Load both STLs as ONE object with two parts in the slicer (Bambu/Orca/Prusa:
// add the labels file as a part) and give the labels the second filament.
module caps_print(mode = "body") {
    for (i = [0:len(KEYS) - 1]) {
        k = KEYS[i];
        c = (k[1] == "ring" || k[1] == "ok") ? DPAD_C :
            (k[1] == "volL") ? [VOL_C[0] - VOL_BAR[0] / 4, VOL_C[1]] :
            (k[1] == "volR") ? [VOL_C[0] + VOL_BAR[0] / 4, VOL_C[1]] : k[2];
        ox = (i % 5) * 36;
        oy = -floor(i / 5) * 36;
        if (mode == "body") cap_on_bed(k, ox, oy, c) cap(k);
        else cap_on_bed(k, ox, oy, c) cap_label(k);
    }
    if (mode == "body") cap_on_bed(PWR_K, 5 * 36, 0, PWR_KEY) pwr_cap();
}

// ---------------------------------------------------------------- stand-ins for checking
module panel() {       // LCD (backlight outline) + touch glass
    translate([LCD[0], -LCD[1] - LCD[3], Z_LCD_BOT]) cube([LCD[2], LCD[3], LCD_T]);
    translate([0, 0, Z_LENS_TOP - CTP_T]) linear_extrude(CTP_T) rrect([LENS[0], LENS[1]], LENS[2], LENS_C);
}
module panel_fpc() {   // the 50-pin FPC folded under the LCD into the ZIF, parts area 1.5 mm
    x0 = FPC[0]; w = FPC[1];
    translate([x0, -LENS_Y1, Z_BP_TOP]) cube([w, LENS_Y1 - FPC[2], 0.3]);                  // flat run to the connector
    translate([FPC[6], -LENS_Y1, Z_BP_TOP]) cube([FPC[7], LENS_Y1 - FPC[3], 1.5]);          // wide section + parts strip
    // the fold, as wide as the wide section and bulged by half the slack
    bend = FPC[4] + FPC[5] + 0.15 + FPC[8] / 2;
    translate([FPC[6], -(LENS_Y1 + bend), Z_BP_TOP + 0.6]) cube([FPC[7], bend, Z_LCD_BOT + LCD_T - Z_BP_TOP - 0.7]);
}
module battery() {
    translate([BATT_C[0] - BATT[0] / 2, -BATT_C[1] - BATT[1] / 2, BACK_T]) cube(BATT);
}
module bp2d() {
    difference() {
        union() {
            outline2d(-BP_INSET);
            translate([USB_TAB[0], -USB_TAB[2]]) square([USB_TAB[1] - USB_TAB[0], 6]);
        }
    }
}
module bp_pcb() {
    translate([0, 0, Z_BP_TOP - BP_T]) linear_extrude(BP_T) difference() {
        bp2d();
        for (p = concat(KEY_HOLES, TOP_BOSSES, BOT_BOSSES)) translate(S(p)) circle(d = 2.2);
    }
}
module bp_switches() {
    for (k = KEYS) translate([k[2][0] - SW_BODY / 2, -k[2][1] - SW_BODY / 2, Z_BP_TOP]) cube([SW_BODY, SW_BODY, SW_HEIGHT]);
    translate([PWR_KEY[0] - SW_BODY / 2, -PWR_KEY[1] - SW_BODY / 2, Z_BP_TOP]) cube([SW_BODY, SW_BODY, SW_HEIGHT]);
}
module bp_irleds() {
    for (x = IR_LED_X) translate([x - 1.15, -(IR_LED_TIP_Y + IR_LED_LEN + 0.6), Z_BP_TOP]) cube([2.3, IR_LED_LEN + 0.6 - 0.85, 2.55]);
}
module bp_usbc() { translate([USB_X - 4.47, -USB_FACE_Y, Z_BP_TOP]) cube([8.94, 7.35, USB_H]); }
module bp_module() {   // ESP32-S3-WROOM-1 on the underside
    translate([MOD[0] - MOD[2] / 2, -MOD[1] - MOD[3] / 2, Z_BP_BOT - MOD[4]]) cube([MOD[2], MOD[3], MOD[4]]);
}
module bp_lra() { translate([MOTOR_C[0], -MOTOR_C[1], Z_BP_BOT - MOTOR_T]) cylinder(d = MOTOR_D, h = MOTOR_T); }
module bp_zif() {      // 50-pin ZIF connector under the panel
    translate([ZIF[0], -ZIF[1] - ZIF[3], Z_BP_TOP]) cube([ZIF[2], ZIF[3], ZIF[4]]);
}
module bp_ics() { for (p = PARTS) translate([p[0] - p[2] / 2, -p[1] - p[3] / 2, Z_BP_TOP]) cube([p[2], p[3], p[4]]); }
module bp_screw_heads() {   // the board screws' pan heads under the board
    for (p = BOARD_SCREWS) translate([p[0], -p[1], Z_BP_BOT - BOARD_HEAD[1]]) cylinder(d = BOARD_HEAD[0], h = BOARD_HEAD[1], $fn = 32);
}
module backplane_envelope() { bp_pcb(); bp_switches(); bp_irleds(); bp_usbc(); bp_module(); bp_lra(); bp_zif(); bp_ics(); bp_screw_heads(); }
module board_envelope() { panel(); panel_fpc(); }

module assembly() {
    color("dimgray") front_shell();
    color("white", 0.5) windows();
    color("gray") back_plate();
    color("white") for (k = KEYS) cap(k);
    color("black") for (k = KEYS) cap_label(k);
    color("white") pwr_cap();
    color("darkgreen", 0.7) backplane_envelope();
    color("navy", 0.5) board_envelope();
    color("orange", 0.6) battery();
}

// For the 3D viewer: export caps by colour group, in place.
names = [];
function in_list(x, l) = len([for (e = l) if (e == x) 1]) > 0;

if (part == "capgroup") { for (k = KEYS) if (in_list(k[0], names)) cap(k); }
else if (part == "pwrcap") pwr_cap();
else if (part == "internals") { board_envelope(); backplane_envelope(); battery(); }
// separate stand-ins for the 3D viewer's labelled X-ray view
else if (part == "v_panel") panel();
else if (part == "v_fpc") panel_fpc();
else if (part == "v_pcb") bp_pcb();
else if (part == "v_switches") bp_switches();
else if (part == "v_irleds") bp_irleds();
else if (part == "v_usbc") bp_usbc();
else if (part == "v_module") bp_module();
else if (part == "v_lra") bp_lra();
else if (part == "v_zif") bp_zif();
else if (part == "v_ics") bp_ics();
else if (part == "v_screws") bp_screw_heads();
else if (part == "v_battery") battery();
else if (part == "front") front_print();
else if (part == "front_inplace") front_shell();
else if (part == "ir_window")       // on the bed flange down, outer face up
    translate([-IR_WINDOW[0], IR_WINDOW[3], WALL]) rotate([90, 0, 0]) ir_window();
else if (part == "sensor_window")   // on the bed pill face down, pegs up
    translate([-SENSOR_WIN[0], -SENSOR_WIN[1], H]) rotate([180, 0, 0]) sensor_window();
else if (part == "windows_inplace") windows();
else if (part == "back") back_plate();
else if (part == "caps") caps_print("body");
else if (part == "caps_labels") caps_print("labels");
else if (part == "labels_inplace") { for (k = KEYS) cap_label(k); }
else if (part == "caps_inplace") { for (k = KEYS) cap(k); pwr_cap(); }
else if (part == "assembly") assembly();
else if (part == "fit_test") {
    // Key area of the front shell only: check cap clearance, insert holes and
    // post height before printing the whole shell. Print face down.
    translate([0, 0, H]) rotate([180, 0, 0]) intersection() {
        front_shell();
        translate([-1, -L - 1, -1]) cube([W + 2, L - PWR_KEY[1] + 5, H + 2]);
    }
}
else if (part == "interference") {
    // everything here should be empty (zero-thickness contacts are fine)
    intersection() { union() { front_shell(); back_plate(); } union() { board_envelope(); battery(); backplane_envelope(); } }
}
else if (part == "windows_vs_parts") {
    // the windows (and the light pipe) against everything inside: should be empty
    intersection() { windows(); union() { back_plate(); board_envelope(); backplane_envelope(); battery(); for (k = KEYS) cap(k); pwr_cap(); } }
}
else if (part == "cap_interference") {
    intersection() { front_shell(); union() { for (k = KEYS) cap(k); pwr_cap(); } }
}
else if (part == "board_vs_bp") {
    // the panel and its folded FPC against the board's top-side parts: should be empty
    intersection() { panel(); union() { bp_switches(); bp_irleds(); bp_usbc(); bp_ics(); bp_zif(); } }
}
else if (part == "cap_vs_parts") {
    // caps and their long stems against the backplane parts: should be empty
    intersection() { union() { for (k = KEYS) cap(k); pwr_cap(); } union() { backplane_envelope(); board_envelope(); } }
}
