#!/usr/bin/env python3
"""Build the Bleep icon font (icons.otf) from icons.json.

Each icon is a 24x24 SVG drawn with 1.6 px round-capped strokes, as in the
design. picosvg turns the strokes into filled outlines; fontTools writes one
glyph per icon at U+E000 upward. lv_font_conv then rasterises the font.

Needs: pip install fonttools picosvg (which brings skia-pathops)
Writes: icons.otf and ../app/ui/icons.h
"""
import json, os, sys
from picosvg.svg import SVG
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.t2CharStringPen import T2CharStringPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path
from pathops import Path, union

HERE = os.path.dirname(os.path.abspath(__file__))
UPM = 960            # 40 units per design pixel
SCALE = UPM / 24
FIRST = 0xE000

icons = json.load(open(os.path.join(HERE, "icons.json")))

def outline(icon):
    fill = 'currentColor' if icon["fill"] else 'none'
    paths = "".join(f'<path d="{d}"/>' for d in icon["paths"])
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="{fill}" '
           f'stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">{paths}</svg>')
    pico = SVG.fromstring(svg.replace("currentColor", "black")).topicosvg()
    return [shape.d for shape in pico.shapes()]

names = [".notdef"] + [i["name"] for i in icons]
cmap, charstrings, metrics = {}, {}, {".notdef": (UPM, 0)}
charstrings[".notdef"] = T2CharStringPen(UPM, None).getCharString()
for n, icon in enumerate(icons):
    pen = T2CharStringPen(UPM, None)
    # SVG is y-down in a 24 box; font is y-up with the em box from 0 to UPM.
    tpen = TransformPen(pen, (SCALE, 0, 0, -SCALE, 0, UPM))
    # Union the shapes: a filled icon's fill and its stroke overlap, and
    # overlapping contours would cancel out when rasterised.
    shapes = []
    for d in outline(icon):
        p = Path()
        parse_path(d, p.getPen())
        # Normalise each shape's contour directions first: a fill and its
        # stroke can wind opposite ways and cancel where they overlap.
        p.simplify(fix_winding=True)
        shapes.append(p)
    union(shapes, tpen)
    charstrings[icon["name"]] = pen.getCharString()
    metrics[icon["name"]] = (UPM, 0)
    cmap[FIRST + n] = icon["name"]

fb = FontBuilder(UPM, isTTF=False)
fb.setupGlyphOrder(names)
fb.setupCharacterMap(cmap)
fb.setupCFF("BleepIcons", {"FullName": "Bleep Icons"}, charstrings, {})
fb.setupHorizontalMetrics(metrics)
fb.setupHorizontalHeader(ascent=UPM, descent=0)
fb.setupNameTable({"familyName": "Bleep Icons", "styleName": "Regular"})
fb.setupOS2(sTypoAscender=UPM, sTypoDescender=0, usWinAscent=UPM, usWinDescent=0)
fb.setupPost()
fb.save(os.path.join(HERE, "icons.otf"))

# C header: one UTF-8 string macro per icon
with open(os.path.join(HERE, "..", "app", "ui", "icons.h"), "w") as h:
    h.write("/* Generated by tools/make_icon_font.py from tools/icons.json. Do not edit. */\n")
    h.write("#pragma once\n\n")
    for n, icon in enumerate(icons):
        cp = FIRST + n
        utf8 = chr(cp).encode("utf-8")
        esc = "".join(f"\\x{b:02X}" for b in utf8)
        h.write(f'#define ICON_{icon["name"].upper():<14} "{esc}"\n')
    h.write(f"\n#define ICON_FIRST 0x{FIRST:04X}\n#define ICON_LAST  0x{FIRST + len(icons) - 1:04X}\n")
print(f"{len(icons)} icons, U+{FIRST:04X}..U+{FIRST + len(icons) - 1:04X}")
